# Question
Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log('Inside the loop', i);
  }
  console.log('Outside the loop');
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?


# Answer
The console.log with not return anything, as it is inside the function. You want it to be outside the brackets so it can call the function properly

# Teacher Feedback
That outside console log will never run because `return` will abandon the loop and the function entirely when it's hit the moment `i > 3`.
